---
- name: Produce registry specificaiton
  set_fact:
    managed_registry_specification: "{{ managed_registry_spec_template }}"

- name: Debug registry specificaiton
  debug:
    var: managed_registry_specification

- name: Notify secured catalog collectors handlers
  command: /bin/true
  notify:
  - handle secured digests collection
  when:
  - managed_registry_secured

- name: Notify insecured catalog collectors handlers
  command: /bin/true
  notify:
  - handle insecured digests collection
  when:
  - not managed_registry_secured

- name: Flush catalog discovery retrieval handlers
  meta: flush_handlers

- name: Notify secured digests removal handlers
  command: /bin/true
  notify:
  - debug first records of accumualted removal collection
  - handle accumulated removal digests from secured
  when:
  - managed_registry_secured

- name: Notify inecured digests removal handlers
  command: /bin/true
  notify:
  - debug first records of accumualted removal collection
  - handle accumulated removal digests from insecured
  when:
  - not managed_registry_secured

- name: Notify cleanup summary report handlers
  command: /bin/true
  notify:
  - handle registry cleanup report processing
