---
- name: Notify secured catalog collectors handlers
  command: /bin/true
  notify:
  - handle secured digests collection
  when:
    - managed_registry_secured

- name: Notify insecured catalog collectors handlers
  command: /bin/true
  notify:
  - handle insecured digests collection
  when:
    - not managed_registry_secured

- name: Flush catalog discovery retrieval handlers
  meta: flush_handlers

- name: Notify digests removal handlers
  command: /bin/true
  notify:
  - debug first records of accumualted removal collection
  - handle accumulated removal digests cleanup
