---
- name: calculate repository tags number
  set_fact:
    repo_tags_number: "{{ (metadata_tags | list | length) }}"

- name: debug repository collection has enough tags to remove
  debug:
    msg: "Repository '{{ metadata_repo }}' has not enough tags to remove"
  when:
  - ( ((repo_tags_number | int) <= (managed_registry_keep_tags | int)) | bool )

- name: handle metadata collection
  include_tasks: collect_removal_digests.yaml
  when:
  - ( ((repo_tags_number | int) > (managed_registry_keep_tags | int)) | bool )

- name: debug accumulated batch size collection
  debug:
    msg: "Accumulated digests batch size after '{{ metadata_repo }}': {{ images_digests_removal_collection | default([]) | list | length }}"
