---
registry_service: registry

default_registry_keep_tags: 1
default_cleanup_batch_size: 5
default_dry_run_mode: false

garbage_collector_enabled: true
garbage_collector_script: /usr/local/bin/garbage-collector
garbage_collector_log_dir: /var/log/regstrygc
garbage_collector_ignore_failures: true

managed_registry_port: "{{ registry_port | default('443') }}"
managed_registry_protocol: "{{ registry_protocol | default('https') }}"
managed_registry_secured: "{{ registry_secured | default(True) | bool }}"
managed_registry_http_url: "{{ managed_registry_protocol }}://{{ registry_server }}:{{ managed_registry_port }}"
managed_catalog_pagination: 1000

managed_dry_run_mode: "{{ dry_run_mode | default(default_dry_run_mode) | bool }}"
managed_cleanup_batch_size: "{{ cleanup_batch_size | default(default_cleanup_batch_size) | int }}"
managed_registry_keep_tags: "{{ (registry_keep_tags | default(default_registry_keep_tags) | int) }}"

default_registry_include_patterns:
- "library"

managed_registry_include_patterns: "{{ include_patterns | default(default_registry_include_patterns) | list }}"

extracted_managed_repos_tags: {}
unfiltered_reposortories_list: []
filtered_reposortories_list: []
images_digests_removal_collection: []
digests_delete_processed_results: []

images_digests_removal_total: 0
images_digests_removal_stats:
  success: 0
  failed: 0
