---
registry_server: k8s-registry.internal
registry_port: 443
registry_protocol: https
registry_username: invtable
registry_password: secret123
registry_default_keep: 1
registry_service: registry

garbage_collector_script: /usr/local/bin/garbage-collector
garbage_collector_log_dir: /var/log/registry-gc

registry_http_url: "{{ registry_protocol }}://{{ registry_server }}:{{ registry_port }}"

managed_dry_run_mode: "{{ dry_run_mode | default(False) | bool }}"
managed_registry_secured: "{{ ( registry_protocol == 'https') | default(false) | bool }}"
managed_registry_keep_tags: "{{ (registry_keep_tags | default(registry_default_keep) | int) }}"

managed_registry_folders:
- name: "library"
  preserve: 2

extracted_managed_repos_tags: {}
unfiltered_reposortories_list: []
filtered_reposortories_list: []
images_digests_removal_collection: []
